#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
app_nb=$YNH_APP_INSTANCE_NUMBER
ssh_port=$(grep "^Port" /etc/ssh/sshd_config | awk '{print $2}')

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..."

#=================================================
# DOWNLOAD SOURCE CODE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

cp $install_dir/other/install.php $install_dir/
chown $app:www-data $install_dir/install.php

cp $install_dir/other/install_2-1_postgresql.sql $install_dir/
chown $app:www-data $install_dir/install_2-1_postgresql.sql

#=================================================
# CREATE SMF USER
#=================================================
ynh_script_progression --message="Configuring system user..."

ynh_system_user_create --username=$app --home_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

nginx_extra_conf_dir="/etc/nginx/conf.d/$domain.d/$app.d"
mkdir -p "$nginx_extra_conf_dir"

# Prepare nginx extra conf
ynh_config_add --template="nginx-php.conf" --destination="$nginx_extra_conf_dir/php.conf"
#YNH_PHP_VERSION="$phpversion"

# Create a dedicated NGINX config
ynh_config_add_nginx
ynh_config_add --template="example-custom-nginx-config.conf" --destination="$nginx_extra_conf_dir/sample.conf"

#=================================================
# SPECIFIC SETUP
#=================================================
# MODIFY A CONFIG FILE
#=================================================
#mkdir -p "$install_dir/www"
#
#if [ $with_sftp -eq 1 ]
#then
#    ynh_config_add --template="../sources/www/index.html" --destination="$install_dir/www/index.html"
#else
#    ynh_config_add --template="../sources/www/index_no_sftp.html" --destination="$install_dir/www/index.html"
#fi

#chown -R $app:www-data "$install_dir"
# Home directory of the user needs to be owned by root to allow
# SFTP connections
#chown root:root "$install_dir"
#setfacl -m g:$app:r-x "$install_dir"
#setfacl -m g:www-data:r-x "$install_dir"
#chmod 750 "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..."

# Create a dedicatedPHP-FPM config
ynh_config_add_phpfpm

#=================================================
# SIMPLE MACHINES CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Simple Machines..."

# Install packages
ynh_composer_exec install

cp $install_dir/other/install.php $install_dir/

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
