#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
ynh_print_info "Version 1: $php_version $phpversion"
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
app_nb=$YNH_APP_INSTANCE_NUMBER
ssh_port=$(grep "^Port" /etc/ssh/sshd_config | awk '{print $2}')

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..."

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..."
#ynh_app_setting_set --app=$app --key=php_version --value=8.4
#ynh_print_info "Version 2: $php_version"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/www" --source_id="simplemachine"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..."

ynh_system_user_create --username=$app --home_dir="$install_dir" --groups="$groups"

#=================================================
# CREATE DATABASE
#=================================================
ynh_script_progression --message="Creating a database..."

db_name=$(ynh_sanitize_dbid --db_name=$app)
db_user=$db_name
db_pwd=$(ynh_string_random --length=30)

ynh_app_setting_set --app=$app --key=db_name --value=$db_name
ynh_app_setting_set --app=$app --key=db_user --value=$db_user
ynh_app_setting_set --app=$app --key=db_pwd --value=$db_pwd

ynh_psql_setup_db --db_user=$db_user --db_name=$db_name --db_pwd=$db_pwd

ynh_print_info "Version 3: $php_version $phpversion"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

nginx_extra_conf_dir="/etc/nginx/conf.d/$domain.d/$app.d"
mkdir -p "$nginx_extra_conf_dir"

# Prepare nginx extra conf
ynh_add_config --template="nginx-php.conf" --destination="$nginx_extra_conf_dir/php.conf"
#YNH_PHP_VERSION="$phpversion"

if [ $custom_error_file -eq 1 ]
then
    # Add the custom error build with the application
    ynh_add_config --template="nginx-code-error.conf" --destination="$nginx_extra_conf_dir/error-code.conf"
fi

# Create a dedicated NGINX config
ynh_add_nginx_config
ynh_add_config --template="example-custom-nginx-config.conf" --destination="$nginx_extra_conf_dir/sample.conf"

#=================================================
# SPECIFIC SETUP
#=================================================
# MODIFY A CONFIG FILE
#=================================================
#mkdir -p "$install_dir/www"
#
#if [ $with_sftp -eq 1 ]
#then
#    ynh_add_config --template="../sources/www/index.html" --destination="$install_dir/www/index.html"
#else
#    ynh_add_config --template="../sources/www/index_no_sftp.html" --destination="$install_dir/www/index.html"
#fi

#chown -R $app:www-data "$install_dir"
# Home directory of the user needs to be owned by root to allow
# SFTP connections
#chown root:root "$install_dir"
#setfacl -m g:$app:r-x "$install_dir"
#setfacl -m g:www-data:r-x "$install_dir"
#chmod 750 "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..."

# Create a dedicatedPHP-FPM config
#ynh_add_fpm_config
ynh_config_add_phpfpm

ynh_print_info "Version 4: $php_version $phpversion"

ynh_composer_install

ynh_print_info "Version 5: $php_version $phpversion"

ynh_composer_exec install

ynh_composer_exec update

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
